# Generated by Django 3.0.7 on 2020-06-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagseguro', '0004_authorization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authorization',
            new_name='RequestAuthorization',
        ),
    ]
