# Generated by Django 3.0.7 on 2020-06-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagseguro', '0005_auto_20200607_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestauthorization',
            name='reference',
            field=models.CharField(blank=True, help_text='Código único para controle', max_length=100, verbose_name='referencia'),
        ),
    ]
