# Generated by Django 3.0.7 on 2020-06-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagseguro', '0006_requestauthorization_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestauthorization',
            name='reference',
            field=models.CharField(blank=True, help_text='Código único para controle', max_length=100, unique=True, verbose_name='referencia'),
        ),
    ]
