# Generated by Django 3.0.7 on 2020-06-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagseguro', '0007_auto_20200607_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Código gerado para redirecionamento.', max_length=100, verbose_name='código')),
                ('date', models.DateTimeField(help_text='Data da solicitação.', verbose_name='Data')),
                ('success', models.BooleanField(db_index=True, default=False, help_text='A solicitação de autorização foi feita com sucesso?', verbose_name='Sucesso')),
                ('message', models.TextField(blank=True, help_text='Mensagem apresentada no caso de erro na solicitação.', verbose_name='Mensagem de erro')),
                ('reference', models.CharField(blank=True, help_text='Código único para controle', max_length=100, unique=True, verbose_name='referencia')),
            ],
            options={
                'verbose_name': 'Autorização',
                'verbose_name_plural': 'Autorizações',
                'ordering': ['-date'],
            },
        ),
    ]
