# Generated by Django 3.0.7 on 2020-06-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagseguro', '0008_authorization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestAuthorization',
        ),
    ]
