# Generated by Django 3.0.7 on 2020-06-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagseguro', '0009_delete_requestauthorization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorization',
            old_name='code',
            new_name='code1',
        ),
    ]
