# Generated by Django 3.0.7 on 2020-06-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagseguro', '0011_auto_20200607_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorization',
            name='code2',
        ),
    ]
